load("//bazel:api.bzl", "mojo_filecheck_test")

package(default_visibility = ["//visibility:public"])

mojo_filecheck_test(
    name = "simple_working_moe",
    srcs = ["simple_working_moe.🔥"],
    deps = [
        "@mojo//:stdlib",
    ],
)